### ISSUE TITLE
Thermal Series Crop Support

### ISSUE THREAD

**Issue by jmdev91** [henkelmax/reap#4]
**Is your feature request related to a problem? Please describe.**
The crops from Thermal Series don't currently work with the harvest and replant feature.

**Describe the solution you'd like**
Any whitelisted crops (including these) should override their normal 'use' behavior, if applicable, to instead behave as this mod intends; that is, harvest, regardless of what item is held, and revert the crop to its freshly-planted state.

**Describe alternatives you've considered**
Only alternative I've tried is the Harvest mod, but that doesn't handle crops which are more than one block in height correctly (such as Thermal Series' corn crop).

**Additional context**
I suspect the problem is caused by these crops having their own 'use' behavior. While that works well for some of the crops, which revert a few growth cycles (eggplants, strawberries, green beans, tomatoes, and peanuts), the rest merely break without replanting.

**Comment by henkelmax** [comment]
The breaking of the crops is a thermal feature. If you add the correct blocks to the whitelist it works perfectly fine.

Here is an example for rice:

``` toml
[crop_harvesting]
	#The blocks that should get harvested by right-clicking
	whitelist = ["minecraft:nether_wart", "minecraft:potatoes", "minecraft:carrots", "minecraft:wheat", "minecraft:beetroots", "minecraft:cocoa","thermal:rice"]
```
